version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  sally:
    docker:
      - image: alpine:3.15
    steps:
      - checkout
      - run:
          command: |
            echo 'double trouble'
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
