version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo 'Hello'

  sally:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo 'double trouble'
workflows:
  bobby_sally:
    jobs:
      - bobby
      - sally
